use std::path::PathBuf;
use std::process::Command;

fn project_root() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .unwrap()
        .to_path_buf()
}

fn load_schema() -> nextsql_core::schema::DatabaseSchema {
    let schema_path = project_root().join("examples/sample-ec-project/schema.json");
    let content = std::fs::read_to_string(&schema_path).unwrap();
    serde_json::from_str(&content).unwrap()
}

#[test]
fn test_generated_code_compiles() {
    let schema = load_schema();
    let source_dir = project_root().join("examples/sample-ec-project");

    let temp_dir = std::env::temp_dir().join("nextsql-compile-test");
    let _ = std::fs::remove_dir_all(&temp_dir);
    let src_dir = temp_dir.join("src");
    std::fs::create_dir_all(&src_dir).unwrap();

    // Generate directly into src/ — codegen produces lib.rs + module files
    let config = nextsql_codegen::CodegenConfig {
        source_dir: source_dir.clone(),
        output_dir: src_dir.clone(),
        backend: "rust".to_string(),
        insert_params_pattern: None,
        update_params_pattern: None,
        package_name: None,
        type_files: vec!["types.nsql".to_string()],
        runtime_crate_path: Some(project_root().join("nextsql-backend-rust/runtime")),
    };
    let result = nextsql_codegen::generate(&config, &schema);
    assert!(
        result.errors.is_empty(),
        "Generation errors: {:?}",
        result.errors
    );

    // Cargo.toml is auto-generated by codegen

    // Run cargo check to verify the generated code compiles
    let output = Command::new("cargo")
        .arg("check")
        .current_dir(&temp_dir)
        .output()
        .expect("Failed to run cargo check");

    let stderr = String::from_utf8_lossy(&output.stderr);
    assert!(
        output.status.success(),
        "Generated code failed to compile:\n{}",
        stderr
    );
}

#[test]
fn test_generated_function_signatures() {
    let schema = load_schema();
    let source_dir = project_root().join("examples/sample-ec-project");

    let temp_dir = std::env::temp_dir().join("nextsql-sig-test");
    let _ = std::fs::remove_dir_all(&temp_dir);
    let src_dir = temp_dir.join("src");
    std::fs::create_dir_all(&src_dir).unwrap();

    let config = nextsql_codegen::CodegenConfig {
        source_dir,
        output_dir: src_dir.clone(),
        backend: "rust".to_string(),
        insert_params_pattern: None,
        update_params_pattern: None,
        package_name: None,
        type_files: vec!["types.nsql".to_string()],
        runtime_crate_path: Some(project_root().join("nextsql-backend-rust/runtime")),
    };
    let result = nextsql_codegen::generate(&config, &schema);
    assert!(result.errors.is_empty(), "Errors: {:?}", result.errors);

    let generated_dir = src_dir.join("generated");
    let customers = std::fs::read_to_string(generated_dir.join("customers.rs")).unwrap();

    // find_customer_by_id returns Vec<Customer> (model struct reuse)
    assert!(
        customers.contains("-> Result<Vec<Customer>,"),
        "find_customer_by_id should return Vec<Customer>, got:\n{}",
        customers
    );
    // create_customer is present
    assert!(
        customers.contains("pub async fn create_customer("),
        "Should have create_customer function"
    );
    // deactivate_customer returns u64 (no RETURNING)
    assert!(
        customers.contains("-> Result<u64,"),
        "deactivate_customer should return u64"
    );
    // Params uses valtype
    assert!(
        customers.contains("pub id: CustomerId"),
        "Params should use CustomerId valtype"
    );

    let orders = std::fs::read_to_string(generated_dir.join("orders.rs")).unwrap();
    // upsert returns Vec<OrderItem>
    assert!(
        orders.contains("-> Result<Vec<OrderItem>,"),
        "upsert should return Vec<OrderItem>"
    );
    // cancel_order is present
    assert!(
        orders.contains("pub async fn cancel_order("),
        "Should have cancel_order function"
    );
}
