mod naming;
mod valtype;
mod type_resolve;
mod emit;
mod query_gen;

use std::collections::{HashMap, HashSet};
use nextsql_core::ast::*;
use nextsql_core::schema::DatabaseSchema;
use crate::sql_gen;
use crate::type_mapping::{nextsql_type_to_rust, to_pascal_case_type};

use valtype::ValTypeRegistry;
use type_resolve::{generate_model_struct};
use valtype::generate_valtype_structs;
use query_gen::{generate_query, generate_mutation};

/// Registry of all input type definitions.
#[derive(Debug, Clone)]
pub(crate) struct InputTypeRegistry {
    pub input_types: HashMap<String, InputType>,
}

impl InputTypeRegistry {
    pub fn from_module(module: &Module) -> Self {
        let mut input_types = HashMap::new();
        for tl in &module.toplevels {
            if let TopLevel::Input(input) = tl {
                input_types.insert(input.name.clone(), input.clone());
            }
        }
        InputTypeRegistry { input_types }
    }

    pub fn get(&self, name: &str) -> Option<&InputType> {
        self.input_types.get(name)
    }
}

/// Extract all ValType definitions from a module (for CLI use).
pub fn extract_valtypes(module: &Module) -> Vec<&ValType> {
    module.toplevels.iter().filter_map(|tl| {
        match tl {
            TopLevel::ValType(vt) => Some(vt),
            _ => None
        }
    }).collect()
}

/// Generated Rust code for a single .nsql file
#[derive(Debug)]
pub struct GeneratedRustFile {
    pub filename: String,
    pub content: String,
    pub errors: Vec<String>,
}

/// A single field in a generated Row struct.
#[derive(Clone)]
struct RowField {
    name: String,
    rust_type: String,
    getter: String,
    /// If set, wrap the getter call with this valtype constructor.
    valtype_wrapper: Option<String>,
    /// If true, the field is a parsed enum type (use .parse().unwrap() on the string getter).
    enum_parse: bool,
}

/// Configuration for struct naming patterns.
#[derive(Debug, Clone)]
pub struct NamingConfig {
    /// Pattern for insert param structs, e.g. "Insert{Table}Params"
    pub insert_params_pattern: String,
    /// Pattern for update changeset structs, e.g. "Update{Table}Params"
    pub update_params_pattern: String,
}

impl Default for NamingConfig {
    fn default() -> Self {
        Self {
            insert_params_pattern: "Insert{Table}Params".to_string(),
            update_params_pattern: "Update{Table}Params".to_string(),
        }
    }
}

impl NamingConfig {
    /// Apply the insert naming pattern with the given table name (PascalCase singular).
    pub fn insert_struct_name(&self, table_pascal: &str) -> String {
        self.insert_params_pattern.replace("{Table}", table_pascal)
    }

    /// Apply the update naming pattern with the given table name (PascalCase singular).
    pub fn update_struct_name(&self, table_pascal: &str) -> String {
        self.update_params_pattern.replace("{Table}", table_pascal)
    }
}

// ── Public entry points ─────────────────────────────────────────────────

/// Generate Rust code from a parsed NextSQL module.
pub fn generate_rust_module(
    module: &Module,
    schema: &DatabaseSchema,
    module_name: &str,
) -> GeneratedRustFile {
    let result = generate_rust_file(module, schema);
    GeneratedRustFile {
        filename: format!("{}.rs", module_name),
        content: result.content,
        errors: result.errors,
    }
}

/// Generate a shared types.rs file containing all valtype definitions from multiple modules.
/// This avoids duplicating valtype structs across generated files.
pub fn generate_valtype_file(modules: &[&Module]) -> GeneratedRustFile {
    let mut out = String::new();
    out.push_str("// AUTO-GENERATED by nextsql. Do not edit.\n\n");

    // Collect all valtypes across modules, deduplicating by name
    let mut all_valtypes: HashMap<String, BuiltInType> = HashMap::new();
    for module in modules {
        for tl in &module.toplevels {
            if let TopLevel::ValType(vt) = tl {
                all_valtypes.entry(vt.name.clone())
                    .or_insert_with(|| vt.base_type.clone());
            }
        }
    }

    // Sort by name for deterministic output
    let mut sorted: Vec<(&String, &BuiltInType)> = all_valtypes.iter().collect();
    sorted.sort_by_key(|(name, _)| (*name).clone());

    for (name, base_type) in sorted {
        let rust_base = nextsql_type_to_rust(&Type::BuiltIn(base_type.clone()));
        out.push_str(&format!("pub struct {}(pub {});\n\n", name, rust_base));
        out.push_str(&format!("impl super::runtime::ToSqlParam for {} {{\n", name));
        out.push_str("    fn as_any(&self) -> &(dyn std::any::Any + Send + Sync) {\n");
        out.push_str("        &self.0\n");
        out.push_str("    }\n");
        out.push_str("}\n\n");
    }

    GeneratedRustFile {
        filename: "types.rs".to_string(),
        content: out,
        errors: Vec::new(),
    }
}

/// Generate the full .rs file content from a module and schema.
/// Includes valtype definitions inline (for backward compatibility / single-file use).
pub fn generate_rust_file(module: &Module, schema: &DatabaseSchema) -> GeneratedRustFile {
    generate_rust_file_with_options(module, schema, false)
}

/// Generate the full .rs file content from a module and schema.
/// When `skip_valtype_generation` is true, valtype structs are not emitted inline
/// (they should be generated in a shared types.rs instead).
pub fn generate_rust_file_with_options(module: &Module, schema: &DatabaseSchema, skip_valtype_generation: bool) -> GeneratedRustFile {
    generate_rust_file_full(module, schema, skip_valtype_generation, &NamingConfig::default())
}

/// Generate the full .rs file content with all options including naming config.
pub fn generate_rust_file_full(module: &Module, schema: &DatabaseSchema, skip_valtype_generation: bool, naming: &NamingConfig) -> GeneratedRustFile {
    let mut out = String::new();
    let mut errors: Vec<String> = Vec::new();
    out.push_str("// AUTO-GENERATED by nextsql. Do not edit.\n\n");

    if skip_valtype_generation {
        out.push_str("use super::types::*;\n\n");
    }

    // Build the valtype registry from the module
    let registry = ValTypeRegistry::from_module(module);

    // Build the relation registry from the module
    let rel_registry = sql_gen::RelationRegistry::from_module(module);

    // Build the input type registry from the module
    let input_registry = InputTypeRegistry::from_module(module);

    // Generate valtype newtype structs (only if not skipping)
    if !skip_valtype_generation {
        generate_valtype_structs(&mut out, &registry);
    }

    // Generate Rust enums for PostgreSQL enum types in the schema
    generate_db_enums(&mut out, schema);

    // Emit input type structs
    for toplevel in &module.toplevels {
        if let TopLevel::Input(input) = toplevel {
            emit::emit_input_struct(&mut out, input, &registry, schema);
        }
    }

    // First pass: generate queries/mutations into a buffer, collecting model table names
    let mut body = String::new();
    let mut model_tables: HashSet<String> = HashSet::new();

    for toplevel in &module.toplevels {
        match toplevel {
            TopLevel::Query(q) => generate_query(&mut body, q, schema, &mut model_tables, &registry, &rel_registry, &mut errors, &input_registry),
            TopLevel::Mutation(m) => generate_mutation(&mut body, m, schema, &mut model_tables, &registry, &rel_registry, naming, &input_registry),
            // With, Relation, ValType, and Input are not directly translated to Rust code here
            TopLevel::With(_) | TopLevel::Relation(_) | TopLevel::ValType(_) | TopLevel::Input(_) => {}
        }
    }

    // Generate model structs at the top for tables that need them
    let mut sorted_tables: Vec<&String> = model_tables.iter().collect();
    sorted_tables.sort();
    for table_name in sorted_tables {
        if let Some(table_schema) = schema.get_table(table_name) {
            generate_model_struct(&mut out, table_schema, &registry, schema);
        }
    }

    // Append the query/mutation code
    out.push_str(&body);

    GeneratedRustFile {
        filename: String::new(),
        content: out,
        errors,
    }
}

/// Generate Rust enum definitions for all PostgreSQL enum types in the schema.
fn generate_db_enums(out: &mut String, schema: &DatabaseSchema) {
    for (enum_name, enum_schema) in &schema.enums {
        let rust_name = to_pascal_case_type(enum_name);

        // Enum definition
        out.push_str("#[derive(Debug, Clone, PartialEq)]\n");
        out.push_str(&format!("pub enum {} {{\n", rust_name));
        for variant in &enum_schema.variants {
            out.push_str(&format!("    {},\n", to_pascal_case_type(variant)));
        }
        out.push_str("}\n\n");

        // Display impl (for SQL parameter binding - converts to the PostgreSQL string value)
        out.push_str(&format!("impl std::fmt::Display for {} {{\n", rust_name));
        out.push_str("    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {\n");
        out.push_str("        match self {\n");
        for variant in &enum_schema.variants {
            out.push_str(&format!(
                "            {}::{} => write!(f, \"{}\"),\n",
                rust_name,
                to_pascal_case_type(variant),
                variant,
            ));
        }
        out.push_str("        }\n");
        out.push_str("    }\n");
        out.push_str("}\n\n");

        // FromStr impl (for parsing from database strings)
        out.push_str(&format!("impl std::str::FromStr for {} {{\n", rust_name));
        out.push_str("    type Err = String;\n");
        out.push_str("    fn from_str(s: &str) -> Result<Self, Self::Err> {\n");
        out.push_str("        match s {\n");
        for variant in &enum_schema.variants {
            out.push_str(&format!(
                "            \"{}\" => Ok({}::{}),\n",
                variant,
                rust_name,
                to_pascal_case_type(variant),
            ));
        }
        out.push_str(&format!(
            "            _ => Err(format!(\"Unknown {} variant: {{}}\", s)),\n",
            rust_name
        ));
        out.push_str("        }\n");
        out.push_str("    }\n");
        out.push_str("}\n\n");

        // ToSqlParam impl
        out.push_str(&format!("impl super::runtime::ToSqlParam for {} {{\n", rust_name));
        out.push_str("    fn as_any(&self) -> &(dyn std::any::Any + Send + Sync) {\n");
        out.push_str("        self\n");
        out.push_str("    }\n");
        out.push_str("}\n\n");
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use nextsql_core::schema::{DatabaseSchema, TableSchema, ColumnSchema};

    // Re-import submodule items needed by tests
    use super::naming::{to_snake_case, to_pascal_case, singularize, table_name_to_model_name};

    /// Helper: build a minimal "users" schema.
    fn users_schema() -> DatabaseSchema {
        let mut schema = DatabaseSchema::new();
        let mut table = TableSchema::new("users".to_string());
        table.add_column(ColumnSchema {
            name: "id".to_string(),
            column_type: Type::BuiltIn(BuiltInType::Uuid),
            nullable: false,
            primary_key: true,
            has_default: true,
            default_value: Some("gen_random_uuid()".to_string()),
        });
        table.add_column(ColumnSchema {
            name: "name".to_string(),
            column_type: Type::BuiltIn(BuiltInType::String),
            nullable: false,
            primary_key: false,
            has_default: false,
            default_value: None,
        });
        table.add_column(ColumnSchema {
            name: "email".to_string(),
            column_type: Type::BuiltIn(BuiltInType::String),
            nullable: false,
            primary_key: false,
            has_default: false,
            default_value: None,
        });
        schema.add_table(table);
        schema
    }

    #[test]
    fn test_to_snake_case() {
        assert_eq!(to_snake_case("findUserById"), "find_user_by_id");
        assert_eq!(to_snake_case("insertUser"), "insert_user");
        assert_eq!(to_snake_case("listAll"), "list_all");
        assert_eq!(to_snake_case("a"), "a");
    }

    #[test]
    fn test_to_pascal_case() {
        assert_eq!(to_pascal_case("findUserById"), "FindUserById");
        assert_eq!(to_pascal_case("insertUser"), "InsertUser");
    }

    #[test]
    fn test_generate_simple_query() {
        let schema = users_schema();

        // query findUserById($id: uuid) {
        //   from(users)
        //   .where(users.id == $id)
        //   .select(users.id, users.name, users.email)
        // }
        let module = Module {
            toplevels: vec![TopLevel::Query(Query {
                decl: QueryDecl {
                    name: "findUserById".to_string(),
                    arguments: vec![Argument {
                        name: "id".to_string(),
                        typ: Type::BuiltIn(BuiltInType::Uuid),
                    }],
                },
                body: QueryBody {
                    statements: vec![QueryStatement::Select(SelectStatement {
                        from: FromExpr {
                            table: "users".to_string(),
                            joins: vec![],
                            span: None,
                        },
                        clauses: vec![
                            QueryClause::Where(Expression::Binary {
                                left: Box::new(Expression::Atomic(AtomicExpression::Column(
                                    Column::ExplicitTarget(
                                        "users".to_string(),
                                        "id".to_string(),
                                        None,
                                    ),
                                ))),
                                op: BinaryOp::Equal,
                                right: Box::new(Expression::Atomic(AtomicExpression::Variable(
                                    Variable {
                                        name: "id".to_string(),
                                        span: None,
                                    },
                                ))),
                            }),
                            QueryClause::Select(vec![
                                SelectExpression {
                                    expr: Expression::Atomic(AtomicExpression::Column(
                                        Column::ExplicitTarget(
                                            "users".to_string(),
                                            "id".to_string(),
                                            None,
                                        ),
                                    )),
                                    alias: None,
                                },
                                SelectExpression {
                                    expr: Expression::Atomic(AtomicExpression::Column(
                                        Column::ExplicitTarget(
                                            "users".to_string(),
                                            "name".to_string(),
                                            None,
                                        ),
                                    )),
                                    alias: None,
                                },
                                SelectExpression {
                                    expr: Expression::Atomic(AtomicExpression::Column(
                                        Column::ExplicitTarget(
                                            "users".to_string(),
                                            "email".to_string(),
                                            None,
                                        ),
                                    )),
                                    alias: None,
                                },
                            ]),
                        ],
                        unions: vec![],
                    })],
                },
            })],
        };

        let result = generate_rust_file(&module, &schema).content;

        // Verify header
        assert!(result.contains("// AUTO-GENERATED by nextsql. Do not edit."));

        // Function should take individual params
        assert!(result.contains("id: &uuid::Uuid,"));
        // Should NOT have a Params struct
        assert!(!result.contains("pub struct FindUserByIdParams {"));
        assert!(!result.contains("to_params"));

        // Verify Row struct
        assert!(result.contains("pub struct FindUserByIdRow {"));
        assert!(result.contains("pub id: uuid::Uuid,"));
        assert!(result.contains("pub name: String,"));
        assert!(result.contains("pub email: String,"));

        // Verify from_row
        assert!(result.contains("pub fn from_row(row: &dyn super::runtime::Row) -> Self"));
        assert!(result.contains("row.get_uuid(0)"));
        assert!(result.contains("row.get_string(1)"));
        assert!(result.contains("row.get_string(2)"));

        // Verify executor function
        assert!(result.contains("pub async fn find_user_by_id("));
        assert!(result.contains("client.query("));
        assert!(result.contains("FindUserByIdRow::from_row(row)"));
    }

    #[test]
    fn test_generate_insert_mutation_with_returning() {
        let schema = users_schema();

        // mutation insertUser($name: string, $email: string) {
        //   insert(users)
        //   .value({ name: $name, email: $email })
        //   .returning(users.*)
        // }
        let mut values = std::collections::HashMap::new();
        values.insert(
            "name".to_string(),
            Expression::Atomic(AtomicExpression::Variable(Variable {
                name: "name".to_string(),
                span: None,
            })),
        );
        values.insert(
            "email".to_string(),
            Expression::Atomic(AtomicExpression::Variable(Variable {
                name: "email".to_string(),
                span: None,
            })),
        );

        let module = Module {
            toplevels: vec![TopLevel::Mutation(Mutation {
                decl: MutationDecl {
                    name: "insertUser".to_string(),
                    arguments: vec![
                        Argument {
                            name: "name".to_string(),
                            typ: Type::BuiltIn(BuiltInType::String),
                        },
                        Argument {
                            name: "email".to_string(),
                            typ: Type::BuiltIn(BuiltInType::String),
                        },
                    ],
                },
                body: MutationBody {
                    items: vec![MutationBodyItem::Mutation(MutationStatement::Insert(
                        Insert {
                            into: Target { name: "users".to_string(), span: None },
                            values: vec![Expression::Atomic(AtomicExpression::Literal(
                                Literal::Object(ObjectLiteralExpression { fields: values, span: None }),
                            ))],
                            on_conflict: None,
                            returning: Some(vec![Column::WildcardOf(
                                "users".to_string(),
                                None,
                            )]),
                        },
                    ))],
                },
            })],
        };

        let result = generate_rust_file(&module, &schema).content;

        // Function should take individual params
        assert!(result.contains("name: &String,"));
        assert!(result.contains("email: &String,"));
        assert!(!result.contains("pub struct InsertUserParams {"));

        // Verify model struct is used (RETURNING users.* reuses User model)
        assert!(result.contains("pub struct User {"));
        assert!(!result.contains("pub struct InsertUserRow {"));

        // Verify executor uses client.query (because RETURNING is present)
        assert!(result.contains("pub async fn insert_user("));
        assert!(result.contains("client.query("));
        assert!(result.contains("User::from_row(row)"));
    }

    #[test]
    fn test_generate_delete_without_returning() {
        let schema = users_schema();

        // mutation deleteUser($id: uuid) {
        //   delete(users)
        //   .where(users.id == $id)
        // }
        let module = Module {
            toplevels: vec![TopLevel::Mutation(Mutation {
                decl: MutationDecl {
                    name: "deleteUser".to_string(),
                    arguments: vec![Argument {
                        name: "id".to_string(),
                        typ: Type::BuiltIn(BuiltInType::Uuid),
                    }],
                },
                body: MutationBody {
                    items: vec![MutationBodyItem::Mutation(MutationStatement::Delete(
                        Delete {
                            target: Target {
                                name: "users".to_string(),
                                span: None,
                            },
                            where_clause: Some(Expression::Binary {
                                left: Box::new(Expression::Atomic(AtomicExpression::Column(
                                    Column::ExplicitTarget(
                                        "users".to_string(),
                                        "id".to_string(),
                                        None,
                                    ),
                                ))),
                                op: BinaryOp::Equal,
                                right: Box::new(Expression::Atomic(AtomicExpression::Variable(
                                    Variable {
                                        name: "id".to_string(),
                                        span: None,
                                    },
                                ))),
                            }),
                            returning: None,
                        },
                    ))],
                },
            })],
        };

        let result = generate_rust_file(&module, &schema).content;

        // Function should take individual params
        assert!(result.contains("id: &uuid::Uuid,"));
        assert!(!result.contains("pub struct DeleteUserParams {"));

        // No Row struct for DELETE without RETURNING
        assert!(!result.contains("pub struct DeleteUserRow {"));

        // Verify executor uses client.execute (no RETURNING)
        assert!(result.contains("pub async fn delete_user("));
        assert!(result.contains("client.execute("));
        assert!(result.contains("Result<u64,"));
    }

    #[test]
    fn test_param_ordering_matches_sql() {
        let schema = users_schema();

        // Build a query with 2 params to verify ordering
        let module = Module {
            toplevels: vec![TopLevel::Query(Query {
                decl: QueryDecl {
                    name: "findUser".to_string(),
                    arguments: vec![
                        Argument {
                            name: "name".to_string(),
                            typ: Type::BuiltIn(BuiltInType::String),
                        },
                        Argument {
                            name: "email".to_string(),
                            typ: Type::BuiltIn(BuiltInType::String),
                        },
                    ],
                },
                body: QueryBody {
                    statements: vec![QueryStatement::Select(SelectStatement {
                        from: FromExpr {
                            table: "users".to_string(),
                            joins: vec![],
                            span: None,
                        },
                        clauses: vec![
                            QueryClause::Where(Expression::Binary {
                                left: Box::new(Expression::Binary {
                                    left: Box::new(Expression::Atomic(
                                        AtomicExpression::Column(Column::ExplicitTarget(
                                            "users".to_string(),
                                            "name".to_string(),
                                            None,
                                        )),
                                    )),
                                    op: BinaryOp::Equal,
                                    right: Box::new(Expression::Atomic(
                                        AtomicExpression::Variable(Variable {
                                            name: "name".to_string(),
                                            span: None,
                                        }),
                                    )),
                                }),
                                op: BinaryOp::And,
                                right: Box::new(Expression::Binary {
                                    left: Box::new(Expression::Atomic(
                                        AtomicExpression::Column(Column::ExplicitTarget(
                                            "users".to_string(),
                                            "email".to_string(),
                                            None,
                                        )),
                                    )),
                                    op: BinaryOp::Equal,
                                    right: Box::new(Expression::Atomic(
                                        AtomicExpression::Variable(Variable {
                                            name: "email".to_string(),
                                            span: None,
                                        }),
                                    )),
                                }),
                            }),
                            QueryClause::Select(vec![SelectExpression {
                                expr: Expression::Atomic(AtomicExpression::Column(
                                    Column::WildcardOf("users".to_string(), None),
                                )),
                                alias: None,
                            }]),
                        ],
                        unions: vec![],
                    })],
                },
            })],
        };

        let result = generate_rust_file(&module, &schema).content;

        // Individual params
        assert!(result.contains("name: &String,"));
        assert!(result.contains("email: &String,"));
        assert!(!result.contains("&self."));

        // Verify the SQL contains both placeholders
        assert!(result.contains("$1"));
        assert!(result.contains("$2"));

        // This query uses users.* on a single table, so it should use User model
        assert!(result.contains("pub struct User {"));
        assert!(!result.contains("pub struct FindUserRow {"));
        assert!(result.contains("User::from_row(row)"));
    }

    #[test]
    fn test_simple_wildcard_uses_model_struct() {
        let schema = users_schema();

        // query findAllUsers() { from(users).select(users.*) }
        let module = Module {
            toplevels: vec![TopLevel::Query(Query {
                decl: QueryDecl {
                    name: "findAllUsers".to_string(),
                    arguments: vec![],
                },
                body: QueryBody {
                    statements: vec![QueryStatement::Select(SelectStatement {
                        from: FromExpr {
                            table: "users".to_string(),
                            joins: vec![],
                            span: None,
                        },
                        clauses: vec![QueryClause::Select(vec![SelectExpression {
                            expr: Expression::Atomic(AtomicExpression::Column(
                                Column::WildcardOf("users".to_string(), None),
                            )),
                            alias: None,
                        }])],
                        unions: vec![],
                    })],
                },
            })],
        };

        let result = generate_rust_file(&module, &schema).content;

        // Should generate User model struct, not FindAllUsersRow
        assert!(result.contains("pub struct User {"));
        assert!(!result.contains("pub struct FindAllUsersRow {"));
        assert!(result.contains("User::from_row(row)"));

        // Model struct should have all columns
        assert!(result.contains("pub id: uuid::Uuid,"));
        assert!(result.contains("pub name: String,"));
        assert!(result.contains("pub email: String,"));
    }

    #[test]
    fn test_partial_select_uses_row_struct() {
        let schema = users_schema();

        // query findUserNames() { from(users).select(users.name) }
        let module = Module {
            toplevels: vec![TopLevel::Query(Query {
                decl: QueryDecl {
                    name: "findUserNames".to_string(),
                    arguments: vec![],
                },
                body: QueryBody {
                    statements: vec![QueryStatement::Select(SelectStatement {
                        from: FromExpr {
                            table: "users".to_string(),
                            joins: vec![],
                            span: None,
                        },
                        clauses: vec![QueryClause::Select(vec![SelectExpression {
                            expr: Expression::Atomic(AtomicExpression::Column(
                                Column::ExplicitTarget(
                                    "users".to_string(),
                                    "name".to_string(),
                                    None,
                                ),
                            )),
                            alias: None,
                        }])],
                        unions: vec![],
                    })],
                },
            })],
        };

        let result = generate_rust_file(&module, &schema).content;

        // Should generate FindUserNamesRow, not User
        assert!(result.contains("pub struct FindUserNamesRow {"));
        assert!(!result.contains("pub struct User {"));
        assert!(result.contains("FindUserNamesRow::from_row(row)"));
    }

    #[test]
    fn test_join_query_uses_row_struct() {
        let mut schema = users_schema();
        // Add posts table
        let mut posts = TableSchema::new("posts".to_string());
        posts.add_column(ColumnSchema {
            name: "id".to_string(),
            column_type: Type::BuiltIn(BuiltInType::Uuid),
            nullable: false,
            primary_key: true,
            has_default: true,
            default_value: None,
        });
        posts.add_column(ColumnSchema {
            name: "title".to_string(),
            column_type: Type::BuiltIn(BuiltInType::String),
            nullable: false,
            primary_key: false,
            has_default: false,
            default_value: None,
        });
        posts.add_column(ColumnSchema {
            name: "user_id".to_string(),
            column_type: Type::BuiltIn(BuiltInType::Uuid),
            nullable: false,
            primary_key: false,
            has_default: false,
            default_value: None,
        });
        schema.add_table(posts);

        // query findUserWithPosts($id: uuid) {
        //   from(users.innerJoin(posts, users.id == posts.user_id))
        //   .where(users.id == $id)
        //   .select(users.*)
        // }
        let module = Module {
            toplevels: vec![TopLevel::Query(Query {
                decl: QueryDecl {
                    name: "findUserWithPosts".to_string(),
                    arguments: vec![Argument {
                        name: "id".to_string(),
                        typ: Type::BuiltIn(BuiltInType::Uuid),
                    }],
                },
                body: QueryBody {
                    statements: vec![QueryStatement::Select(SelectStatement {
                        from: FromExpr {
                            table: "users".to_string(),
                            joins: vec![JoinExpr {
                                join_type: JoinType::Inner,
                                table: "posts".to_string(),
                                condition: Expression::Binary {
                                    left: Box::new(Expression::Atomic(
                                        AtomicExpression::Column(Column::ExplicitTarget(
                                            "users".to_string(),
                                            "id".to_string(),
                                            None,
                                        )),
                                    )),
                                    op: BinaryOp::Equal,
                                    right: Box::new(Expression::Atomic(
                                        AtomicExpression::Column(Column::ExplicitTarget(
                                            "posts".to_string(),
                                            "user_id".to_string(),
                                            None,
                                        )),
                                    )),
                                },
                                span: None,
                            }],
                            span: None,
                        },
                        clauses: vec![
                            QueryClause::Where(Expression::Binary {
                                left: Box::new(Expression::Atomic(AtomicExpression::Column(
                                    Column::ExplicitTarget(
                                        "users".to_string(),
                                        "id".to_string(),
                                        None,
                                    ),
                                ))),
                                op: BinaryOp::Equal,
                                right: Box::new(Expression::Atomic(
                                    AtomicExpression::Variable(Variable {
                                        name: "id".to_string(),
                                        span: None,
                                    }),
                                )),
                            }),
                            QueryClause::Select(vec![SelectExpression {
                                expr: Expression::Atomic(AtomicExpression::Column(
                                    Column::WildcardOf("users".to_string(), None),
                                )),
                                alias: None,
                            }]),
                        ],
                        unions: vec![],
                    })],
                },
            })],
        };

        let result = generate_rust_file(&module, &schema).content;

        // Even though it's users.*, the query has a JOIN so it should use Row struct
        assert!(result.contains("pub struct FindUserWithPostsRow {"));
        assert!(!result.contains("pub struct User {"));
        assert!(result.contains("FindUserWithPostsRow::from_row(row)"));
    }

    #[test]
    fn test_mutation_returning_wildcard_uses_model() {
        let schema = users_schema();

        // mutation deleteUserReturning($id: uuid) {
        //   delete(users)
        //   .where(users.id == $id)
        //   .returning(users.*)
        // }
        let module = Module {
            toplevels: vec![TopLevel::Mutation(Mutation {
                decl: MutationDecl {
                    name: "deleteUserReturning".to_string(),
                    arguments: vec![Argument {
                        name: "id".to_string(),
                        typ: Type::BuiltIn(BuiltInType::Uuid),
                    }],
                },
                body: MutationBody {
                    items: vec![MutationBodyItem::Mutation(MutationStatement::Delete(
                        Delete {
                            target: Target {
                                name: "users".to_string(),
                                span: None,
                            },
                            where_clause: Some(Expression::Binary {
                                left: Box::new(Expression::Atomic(AtomicExpression::Column(
                                    Column::ExplicitTarget(
                                        "users".to_string(),
                                        "id".to_string(),
                                        None,
                                    ),
                                ))),
                                op: BinaryOp::Equal,
                                right: Box::new(Expression::Atomic(AtomicExpression::Variable(
                                    Variable {
                                        name: "id".to_string(),
                                        span: None,
                                    },
                                ))),
                            }),
                            returning: Some(vec![Column::WildcardOf(
                                "users".to_string(),
                                None,
                            )]),
                        },
                    ))],
                },
            })],
        };

        let result = generate_rust_file(&module, &schema).content;

        // Should use User model struct, not DeleteUserReturningRow
        assert!(result.contains("pub struct User {"));
        assert!(!result.contains("pub struct DeleteUserReturningRow {"));
        assert!(result.contains("User::from_row(row)"));
    }

    #[test]
    fn test_table_name_to_model_name() {
        assert_eq!(table_name_to_model_name("users"), "User");
        assert_eq!(table_name_to_model_name("posts"), "Post");
        assert_eq!(table_name_to_model_name("application_headers"), "ApplicationHeader");
        assert_eq!(table_name_to_model_name("statuses"), "Status");
        assert_eq!(table_name_to_model_name("addresses"), "Address");
        assert_eq!(table_name_to_model_name("businesses"), "Business");
    }

    #[test]
    fn test_singularize() {
        assert_eq!(singularize("users"), "user");
        assert_eq!(singularize("posts"), "post");
        assert_eq!(singularize("s"), "s");
        assert_eq!(singularize("data"), "data");
        // -es endings
        assert_eq!(singularize("addresses"), "address");
        assert_eq!(singularize("statuses"), "status");
        assert_eq!(singularize("businesses"), "business");
        assert_eq!(singularize("boxes"), "box");
        assert_eq!(singularize("watches"), "watch");
        assert_eq!(singularize("crashes"), "crash");
        assert_eq!(singularize("buzzes"), "buzz");
    }

    #[test]
    fn test_valtype_struct_generation() {
        let input = r#"
            valtype UserId = uuid for users.id

            query findAllUsers() {
                from(users)
                .select(users.*)
            }
        "#;
        let module = nextsql_core::parser::parse_module(input).unwrap();
        let mut schema = DatabaseSchema::new();
        let mut table = TableSchema::new("users".to_string());
        table.add_column(ColumnSchema {
            name: "id".to_string(),
            column_type: Type::BuiltIn(BuiltInType::Uuid),
            nullable: false,
            primary_key: true,
            has_default: true,
            default_value: Some("gen_random_uuid()".to_string()),
        });
        table.add_column(ColumnSchema {
            name: "name".to_string(),
            column_type: Type::BuiltIn(BuiltInType::String),
            nullable: false,
            primary_key: false,
            has_default: false,
            default_value: None,
        });
        schema.add_table(table);

        let result = generate_rust_file(&module, &schema).content;
        // Verify valtype struct is generated
        assert!(result.contains("pub struct UserId(pub uuid::Uuid)"), "missing valtype struct: {}", result);
        // Verify ToSqlParam impl
        assert!(result.contains("impl super::runtime::ToSqlParam for UserId"), "missing ToSqlParam impl: {}", result);
        // Verify User model uses UserId for id field
        assert!(result.contains("pub id: UserId"), "id should be UserId: {}", result);
        // Verify from_row wraps with UserId
        assert!(result.contains("UserId(row.get_uuid(0))"), "from_row should wrap with UserId: {}", result);
    }

    #[test]
    fn test_valtype_relation_inference() {
        let input = r#"
            valtype UserId = uuid for users.id

            relation author for posts returning users {
                posts.author_id == users.id
            }

            query findAllPosts() {
                from(posts)
                .select(posts.*)
            }
        "#;
        let module = nextsql_core::parser::parse_module(input).unwrap();
        let mut schema = DatabaseSchema::new();
        // Add users table
        let mut users = TableSchema::new("users".to_string());
        users.add_column(ColumnSchema {
            name: "id".to_string(),
            column_type: Type::BuiltIn(BuiltInType::Uuid),
            nullable: false,
            primary_key: true,
            has_default: true,
            default_value: Some("gen_random_uuid()".to_string()),
        });
        schema.add_table(users);
        // Add posts table
        let mut posts = TableSchema::new("posts".to_string());
        posts.add_column(ColumnSchema {
            name: "id".to_string(),
            column_type: Type::BuiltIn(BuiltInType::Uuid),
            nullable: false,
            primary_key: true,
            has_default: true,
            default_value: Some("gen_random_uuid()".to_string()),
        });
        posts.add_column(ColumnSchema {
            name: "author_id".to_string(),
            column_type: Type::BuiltIn(BuiltInType::Uuid),
            nullable: false,
            primary_key: false,
            has_default: false,
            default_value: None,
        });
        posts.add_column(ColumnSchema {
            name: "title".to_string(),
            column_type: Type::BuiltIn(BuiltInType::String),
            nullable: false,
            primary_key: false,
            has_default: false,
            default_value: None,
        });
        schema.add_table(posts);

        let result = generate_rust_file(&module, &schema).content;
        // posts.author_id should be inferred as UserId from the relation
        assert!(result.contains("pub author_id: UserId"), "author_id should be UserId: {}", result);
    }

    #[test]
    fn test_valtype_in_params() {
        let input = r#"
            valtype UserId = uuid for users.id

            query findUserById($id: UserId) {
                from(users)
                .where(users.id == $id)
                .select(users.*)
            }
        "#;
        let module = nextsql_core::parser::parse_module(input).unwrap();
        let mut schema = DatabaseSchema::new();
        let mut table = TableSchema::new("users".to_string());
        table.add_column(ColumnSchema {
            name: "id".to_string(),
            column_type: Type::BuiltIn(BuiltInType::Uuid),
            nullable: false,
            primary_key: true,
            has_default: true,
            default_value: None,
        });
        table.add_column(ColumnSchema {
            name: "name".to_string(),
            column_type: Type::BuiltIn(BuiltInType::String),
            nullable: false,
            primary_key: false,
            has_default: false,
            default_value: None,
        });
        schema.add_table(table);

        let result = generate_rust_file(&module, &schema).content;
        // Params should use UserId
        assert!(result.contains("pub id: UserId"), "params id should be UserId: {}", result);
    }

    #[test]
    fn test_aggregate_fields_use_correct_types() {
        let input = r#"
query countOrdersByStatus() {
  from(orders)
  .groupBy(orders.status)
  .aggregate(
    order_count: COUNT(orders.id),
    total_amount: SUM(orders.amount),
    avg_amount: AVG(orders.amount),
    min_amount: MIN(orders.amount),
    max_amount: MAX(orders.amount)
  )
  .select(orders.status, order_count, total_amount, avg_amount, min_amount, max_amount)
}
"#;
        let module = nextsql_core::parser::parse_module(input).expect("parse failed");
        let mut schema = DatabaseSchema::new();
        let mut table = TableSchema::new("orders".to_string());
        table.add_column(ColumnSchema {
            name: "id".to_string(),
            column_type: Type::BuiltIn(BuiltInType::Uuid),
            nullable: false, primary_key: true, has_default: true, default_value: None,
        });
        table.add_column(ColumnSchema {
            name: "status".to_string(),
            column_type: Type::BuiltIn(BuiltInType::String),
            nullable: false, primary_key: false, has_default: false, default_value: None,
        });
        table.add_column(ColumnSchema {
            name: "amount".to_string(),
            column_type: Type::BuiltIn(BuiltInType::F64),
            nullable: false, primary_key: false, has_default: false, default_value: None,
        });
        schema.add_table(table);

        let result = generate_rust_file(&module, &schema);
        let content = &result.content;

        // COUNT should produce i64
        assert!(content.contains("pub order_count: i64"), "COUNT should produce i64, got:\n{}", content);
        // SUM over f64 column should produce f64
        assert!(content.contains("pub total_amount: f64"), "SUM over f64 should produce f64, got:\n{}", content);
        // AVG should produce f64
        assert!(content.contains("pub avg_amount: f64"), "AVG should produce f64, got:\n{}", content);
        // MIN should produce f64
        assert!(content.contains("pub min_amount: f64"), "MIN should produce f64, got:\n{}", content);
        // MAX should produce f64
        assert!(content.contains("pub max_amount: f64"), "MAX should produce f64, got:\n{}", content);
        // status should remain String (from schema)
        assert!(content.contains("pub status: String"), "status should remain String");
    }

    #[test]
    fn test_change_set_codegen() {
        let input = r#"
            valtype AddressId = uuid for addresses.id

            mutation updateAddress($id: AddressId, $changes: ChangeSet<addresses>) {
                update(addresses)
                .where(addresses.id == $id)
                .set($changes)
            }
        "#;
        let module = nextsql_core::parser::parse_module(input).unwrap();
        let mut schema = DatabaseSchema::new();
        let mut table = TableSchema::new("addresses".to_string());
        table.add_column(ColumnSchema {
            name: "id".to_string(),
            column_type: Type::BuiltIn(BuiltInType::Uuid),
            nullable: false,
            primary_key: true,
            has_default: true,
            default_value: None,
        });
        table.add_column(ColumnSchema {
            name: "city".to_string(),
            column_type: Type::BuiltIn(BuiltInType::String),
            nullable: false,
            primary_key: false,
            has_default: false,
            default_value: None,
        });
        table.add_column(ColumnSchema {
            name: "notes".to_string(),
            column_type: Type::BuiltIn(BuiltInType::String),
            nullable: true,
            primary_key: false,
            has_default: false,
            default_value: None,
        });
        schema.add_table(table);

        let result = generate_rust_file(&module, &schema);
        let content = &result.content;

        // Should have UpdateField in the Changes struct
        assert!(content.contains("UpdateField<String>"), "city should be UpdateField<String>: {}", content);
        assert!(content.contains("UpdateField<Option<String>>"), "notes should be UpdateField<Option<String>>: {}", content);
        // Should have Default impl
        assert!(content.contains("impl Default for"), "Should have Default impl: {}", content);
        assert!(content.contains("Unchanged"), "Default should use Unchanged: {}", content);
        // Should have dynamic SQL building
        assert!(content.contains("set_parts"), "Should build SET parts dynamically: {}", content);
        assert!(content.contains("is_set()"), "Should check is_set(): {}", content);
        // Should have ChangeSet struct (named via NamingConfig: Update{Table}Params)
        assert!(content.contains("pub struct UpdateAddresse") || content.contains("pub struct UpdateAddress"),
            "Should have ChangeSet struct: {}", content);
        // Should have Params struct with changes field
        assert!(content.contains("pub changes: Update"), "Should have changes field in Params: {}", content);
        // Should have id param with valtype
        assert!(content.contains("pub id: AddressId"), "Should have id with AddressId type: {}", content);
        // Should return Result<u64>
        assert!(content.contains("Result<u64,"), "Should return u64 for non-returning: {}", content);
    }

    #[test]
    fn test_change_set_codegen_with_returning() {
        let input = r#"
            mutation updateAddress($id: uuid, $changes: ChangeSet<addresses>) {
                update(addresses)
                .where(addresses.id == $id)
                .set($changes)
                .returning(addresses.*)
            }
        "#;
        let module = nextsql_core::parser::parse_module(input).unwrap();
        let mut schema = DatabaseSchema::new();
        let mut table = TableSchema::new("addresses".to_string());
        table.add_column(ColumnSchema {
            name: "id".to_string(),
            column_type: Type::BuiltIn(BuiltInType::Uuid),
            nullable: false,
            primary_key: true,
            has_default: true,
            default_value: None,
        });
        table.add_column(ColumnSchema {
            name: "city".to_string(),
            column_type: Type::BuiltIn(BuiltInType::String),
            nullable: false,
            primary_key: false,
            has_default: false,
            default_value: None,
        });
        schema.add_table(table);

        let result = generate_rust_file(&module, &schema);
        let content = &result.content;

        // Should have RETURNING with model struct
        assert!(content.contains("pub struct Addresse {") || content.contains("pub struct Address {"),
            "Should have model struct for returning: {}", content);
        // Should return Vec, not u64
        assert!(content.contains("Result<Vec<"), "Should return Vec for returning: {}", content);
        // Should use client.query
        assert!(content.contains("client.query(&sql"), "Should use client.query for returning: {}", content);
    }

    #[test]
    fn test_aliased_select_type_from_schema() {
        // Schema: payees table with expense_id as uuid
        let mut schema = DatabaseSchema::new();
        let mut table = TableSchema::new("payees".to_string());
        table.add_column(ColumnSchema {
            name: "id".to_string(),
            column_type: Type::BuiltIn(BuiltInType::Uuid),
            nullable: false,
            primary_key: true,
            has_default: true,
            default_value: Some("gen_random_uuid()".to_string()),
        });
        table.add_column(ColumnSchema {
            name: "expense_id".to_string(),
            column_type: Type::BuiltIn(BuiltInType::Uuid),
            nullable: false,
            primary_key: false,
            has_default: false,
            default_value: None,
        });
        schema.add_table(table);

        // query getPayee() {
        //   from(payees)
        //   .select(app_id: payees.expense_id)
        // }
        let module = Module {
            toplevels: vec![TopLevel::Query(Query {
                decl: QueryDecl {
                    name: "getPayee".to_string(),
                    arguments: vec![],
                },
                body: QueryBody {
                    statements: vec![QueryStatement::Select(SelectStatement {
                        from: FromExpr {
                            table: "payees".to_string(),
                            joins: vec![],
                            span: None,
                        },
                        clauses: vec![
                            QueryClause::Select(vec![
                                SelectExpression {
                                    expr: Expression::Atomic(AtomicExpression::Column(
                                        Column::ExplicitTarget(
                                            "payees".to_string(),
                                            "expense_id".to_string(),
                                            None,
                                        ),
                                    )),
                                    alias: Some("app_id".to_string()),
                                },
                            ]),
                        ],
                        unions: vec![],
                    })],
                },
            })],
        };

        let result = generate_rust_file(&module, &schema);
        let content = &result.content;

        // Should have app_id as uuid::Uuid, NOT String
        assert!(
            content.contains("pub app_id: uuid::Uuid"),
            "Aliased column should resolve to uuid::Uuid, not String. Got: {}",
            content
        );
        assert!(
            !content.contains("pub app_id: String"),
            "Aliased column should NOT be String. Got: {}",
            content
        );
    }
}
